"""Filter the external Kaggle corpus down to its English rows.

The download under `data/external/customer-support-tickets/raw/` is
multi-lingual: 67,890 rows, of which only 44% are English. The project
standardised on English in Phase 0, so everything downstream reads the
normalised output this module writes rather than the raw CSVs.

Three properties this module is built around:

1. `raw/` is immutable (chmod 444). Nothing here opens it for writing; the
   output goes to a sibling `normalized/` directory so the download stays
   byte-reproducible against the checksums in SOURCE.md.

2. The five files do not share a schema — 5, 15, 16 and 17 columns — and the
   two `german_normalized*` files contain zero English rows. Columns are
   unioned rather than intersected so nothing is silently dropped, and files
   that contribute nothing are reported instead of failing.

3. The multi-lang files overlap: `4-20k` shares English bodies with
   `5-2-50-version`. Deduplication is on `body` rather than `subject`, which is
   empty on 2,607 rows. SOURCE.md claims `body` is always populated; it is not
   — two rows have none, and they bypass the dedupe set rather than collapsing
   into a single "empty" row. That is the difference between 25,055 and the
   25,056 SOURCE.md documents.

License: the Kaggle page was never verified (see SOURCE.md). Output stays
gitignored for that reason.
"""

from __future__ import annotations

import csv
import sys
from dataclasses import dataclass, field
from pathlib import Path

# The multi-lang CSVs carry single fields larger than Python's default 128 KB
# limit; without this the reader raises partway through the biggest file.
csv.field_size_limit(min(sys.maxsize, 2**31 - 1))

DEFAULT_RAW = Path("data/external/customer-support-tickets/raw")
DEFAULT_OUT = Path("data/external/customer-support-tickets/normalized")

LANGUAGE_COLUMNS = {"language", "lang", "locale"}


@dataclass
class FileReport:
    """What one source file contributed."""

    name: str
    rows: int = 0
    english: int = 0
    kept: int = 0
    duplicates: int = 0
    empty_subject: int = 0
    empty_body: int = 0
    languages: dict[str, int] = field(default_factory=dict)


@dataclass
class Report:
    files: list[FileReport] = field(default_factory=list)
    total_rows: int = 0
    total_english: int = 0
    total_kept: int = 0
    total_duplicates: int = 0
    columns: list[str] = field(default_factory=list)

    def as_markdown(self) -> str:
        lines = [
            "# External corpus — English subset",
            "",
            "Generated by `ticketlens-ml external-english`. Derived from the",
            "immutable download in `../raw/`; see `../SOURCE.md` for provenance,",
            "checksums and the unverified-licence warning.",
            "",
            f"- Source rows: **{self.total_rows:,}**",
            f"- English rows: **{self.total_english:,}**",
            f"- Duplicates removed: **{self.total_duplicates:,}**",
            f"- Written: **{self.total_kept:,}**",
            "",
            "## Per file",
            "",
            "| File | Rows | English | Kept | Dupes | Empty subject | Empty body |",
            "|---|---:|---:|---:|---:|---:|---:|",
        ]
        for f in self.files:
            lines.append(
                f"| `{f.name}` | {f.rows:,} | {f.english:,} | {f.kept:,} | "
                f"{f.duplicates:,} | {f.empty_subject:,} | {f.empty_body:,} |"
            )
        lines += [
            "",
            "## Columns",
            "",
            "Union across the source files; a row missing a column gets an empty",
            "string rather than being dropped.",
            "",
            "```",
            ", ".join(self.columns),
            "```",
            "",
            "## Caveats carried forward from SOURCE.md",
            "",
            "- `queue` and `type` do **not** map onto `taxonomy.py`; they are hints.",
            "- The source has no `urgent` priority — it must be derived from text.",
            "- This corpus was the only planned out-of-distribution eval source.",
            "  Split it once and freeze the eval slice before any training use.",
            "",
        ]
        return "\n".join(lines)


def _language_column(columns: list[str]) -> str | None:
    return next((c for c in columns if c.lower() in LANGUAGE_COLUMNS), None)


def _is_english(value: str | None) -> bool:
    # Matches "en", "EN", "en-GB", "english" — but not "" or a missing column,
    # which are treated as unknown rather than assumed English.
    v = (value or "").strip().lower()
    return v.startswith("en")


def filter_english(
    raw_dir: Path = DEFAULT_RAW,
    out_dir: Path = DEFAULT_OUT,
    *,
    dedupe: bool = True,
) -> tuple[Path, Report]:
    """Write the English subset of every CSV in `raw_dir` to one CSV.

    Returns the output path and a report. Raises if `raw_dir` has no CSVs, so
    a mistyped path fails loudly instead of writing an empty file.
    """
    sources = sorted(raw_dir.glob("*.csv"))
    if not sources:
        raise SystemExit(f"No CSV files under {raw_dir}")

    # First pass: union the columns so the writer has a stable header.
    columns: list[str] = []
    for path in sources:
        with path.open(newline="", encoding="utf-8", errors="replace") as fh:
            for name in csv.DictReader(fh).fieldnames or []:
                if name not in columns:
                    columns.append(name)

    report = Report(columns=columns)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "english.csv"
    seen: set[str] = set()

    with out_path.open("w", newline="", encoding="utf-8") as out_fh:
        writer = csv.DictWriter(out_fh, fieldnames=[*columns, "source_file"])
        writer.writeheader()

        for path in sources:
            fr = FileReport(name=path.name)

            with path.open(newline="", encoding="utf-8", errors="replace") as fh:
                reader = csv.DictReader(fh)
                lang_col = _language_column(reader.fieldnames or [])

                for row in reader:
                    fr.rows += 1
                    lang = (row.get(lang_col) or "").strip().lower() if lang_col else ""
                    fr.languages[lang or "(none)"] = (
                        fr.languages.get(lang or "(none)", 0) + 1
                    )

                    if not _is_english(row.get(lang_col) if lang_col else None):
                        continue
                    fr.english += 1

                    body = (row.get("body") or "").strip()
                    if not body:
                        # Two rows in the corpus have no body at all. They are
                        # not duplicates of each other — they may carry
                        # different subjects and labels — so they bypass the
                        # dedupe set rather than collapsing into one row.
                        fr.empty_body += 1
                    elif dedupe:
                        if body in seen:
                            fr.duplicates += 1
                            continue
                        seen.add(body)

                    if not (row.get("subject") or "").strip():
                        fr.empty_subject += 1

                    writer.writerow(
                        {
                            **{c: row.get(c, "") for c in columns},
                            "source_file": path.name,
                        }
                    )
                    fr.kept += 1

            report.files.append(fr)
            report.total_rows += fr.rows
            report.total_english += fr.english
            report.total_kept += fr.kept
            report.total_duplicates += fr.duplicates

    (out_dir / "README.md").write_text(report.as_markdown(), encoding="utf-8")
    return out_path, report
